### ISSUE TITLE
Ensure WCAG2.1 AA compliance as part of adding fast.design to repo

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#2315]
**Describe the bug; what happened?**
See the validation errors produced by Accessibility Insights Edge (Chromium) browser extension.

![image](https://user-images.githubusercontent.com/16669785/66590437-9e24e680-eb45-11e9-8c0b-d0eb1ea9273a.png)

**What are the steps to reproduce the issue?**
1. Launch fast.design home page
2. Click on the Accessibility Insights toolbar icon to scan the page
3. See the results. Also attached.

**What behavior did you expect?**
No errors

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
* OS & Device: [e.g. MacOS, iOS, **Windows**, Linux] on [iPhone 7, PC]
* Browser [e.g. **Edge (Chromium)**, **Chrome**, Safari, FireFox]
* Version [e.g. 1.8.0] **latest**

**Is there any additional context?**
no

**Comment by chrisdholt** [comment]
This will be taken care of as part of the migration to this repo. For now, I'm renaming and updating this to be a task.

**Comment by awentzel** [comment]
Latest FastPass results attached.  These results can be replicated by running "Accessibility Insights for the Web" Anaheim extension on https://www.fast.design  

[Accessibility Insights for Web automated checks result.pdf](https://github.com/microsoft/fast/files/4962839/Accessibility.Insights.for.Web.automated.checks.result.pdf)

**Comment by chrisdholt** [comment]
I think most of the above are fixed; I'll run it later this evening locally if I can to confirm - but we can also run after tomorrow's scheduled deployment.

**Comment by awentzel** [comment]
I gave it a run. Two issues remain. If you have
![Screen Shot 2020-08-13 at 7 22 36 AM](https://user-images.githubusercontent.com/16669785/90146349-cbc65780-dd35-11ea-807e-fa6cf10f7f33.png)

if you have the "Accessibility insights for web", then this link may also work  extension://ghbhpcookfemncgoinjblecnilppimih/DetailsView/detailsView.html?tabId=589

**Comment by awentzel** [comment]
I did a Fast Pass w/ Accessibility Insights (extension) to see how we're looking and found two new issues.  extension://ghbhpcookfemncgoinjblecnilppimih/DetailsView/detailsView.html?tabId=432  

@chrisdholt will these be completed for Thursday or should we punt one release?

**Comment by chrisdholt** [comment]
I can’t see these with the link above, but @khamudom is working on the results of my pass on Sunday before I headed out of town. If it’s done for release, great - if not, I don’t see it as a blocker. Worst case, so long as nothing unpublished on npm is added after this release, we can always release as needed.

**Comment by awentzel** [comment]
Pushing to next release

**Comment by EisenbergEffect** [comment]
Should we push this out again?

**Comment by chrisdholt** [comment]
@eisenbergeffect let's pull this from releases for now. The only outstanding issues for the homepage is color contrast issues which could be related to our recipes. This is an ongoing thing we'll need to be tracking and working on, I think it's a bit of churn to link it to a specific release as we continue to work and drive ahead on it. Not to mention, the docusaurus pages are contributing to overall errors across the fast.design namespace and we technically can't fix those. I'm fine with keeping this open, but it would be great to not link it directly to a given release right now.
