### ISSUE TITLE
So microsoft/fast 2.0 is out or what?

### ISSUE THREAD

**Issue by jurijsk** [microsoft/fast#7034]
I want to share a bit of developer experience with all of you (As ex-dev, trying to get back to coding).

I've decided to try to use the library, so I go to https://fast.design/ and the badge to the top says `2.0 is out`. Drop-down with version number says "2.x". Great, very promising.

Span off new vanilla `vite` project with typescript, ran `npm install @microsoft/fast-element` and copied the code as [Quick Start](https://fast.design/docs/getting-started/quick-start) advices.

Got 3 errors right away:

![Image](https://github.com/user-attachments/assets/9a8b21d0-5f07-4ea4-8ff3-c80ea857e201)

I had to google profusely to just make it compile. Added `experimentalDecorators: true`, switched `module`, `target` to `ES2020` and 'strict' to `false`. Plus change `HelloWorld.define({..,}`) to `HelloWorld.define(HelloWorld, {...})`. Just. To. Make. It. Compile.

And it still was not working after that. The name attribute was not taking the value. You have to find this [issue from 2021](https://github.com/microsoft/fast/issues/5017#issuecomment-962051212) to know that you have to switch `useDefineForClassFields` off, otherwise the whole enterprise is kind of useless.

And only after that, I had a bright idea to check with the version of `fast` I have installed. Of course, it was `1.14.0`, why would I think it would be anything close to `2.0`.

Anyway, so what is up with `v2.0` and is that experience I've just got is what I should expect from `microsoft/fast` as a base for UI I want to build?

**Comment by KingOfTac** [comment]
There was a recent publish of the 1.x version to fix a bug, which with how npm install works the most recently published version of the package is what gets installed by default. You can get the latest 2.x version by specifying the version number when installing i.e. `npm install @microsoft/fast-element@2.0.0`.

@chrisdholt we should probably look into this some more and try to find a way to smooth out this experience. I have noticed this also affects what version is returned when using the CDN link as well.

**Comment by chrisdholt** [comment]
> [@chrisdholt](https://github.com/chrisdholt) we should probably look into this some more and try to find a way to smooth out this experience. I have noticed this also affects what version is returned when using the CDN link as well.

This came up with @janechu yesterday, it's definately top of mind.

**Comment by jurijsk** [comment]
Thank you for looking into this. Please note that the following `tsconfig.ts` settings are also assumed, and it takes a minute to figure out:

```json

{
	"compilerOptions": {
		//...
		"useDefineForClassFields": false,
		"strictPropertyInitialization": false,
		"experimentalDecorators": true
	}
}
```

**Comment by k290** [comment]
Follow the `tsconfig` setup as documented here; https://fast.design/docs/integrations#typescript

[You don't need to add `importHelpers` which then requires you install `tslib` but you can if you want]

**Comment by janechu** [comment]
It seems this issue is resolved per the discussion, our next release will have the `latest` tag, sorry for the confusion!

**Comment by jurijsk** [comment]
Hmm. Today if I run `npm install --save @microsoft/fast-element` I will get `1.14.0`. So that is not resolved for anyone who did not spend an hour trying to "get started". Plus, I do not thing that it is fair to expect someone to read "Get started" and then immediately head to "Integrations", because 2ho does that? Typescript is not even an "integration" for most of the people, this is what you do.

For me the issue is resolved, but you subject newcomers to unnecessary pain and `lit` is one tab away.

**Comment by janechu** [comment]
@jurijsk I've just published 2.0.1, feel free to re-open if you still get this issue.
